### ISSUE TITLE
How can I get the matrix of LIDAR2IMG 

### ISSUE THREAD

**Issue by raozhongyu** [OpenDriveLab/DriveAdapter#3]
Thanks for your great job. I notice the LIDAR2IMG is set as {
    "rgb_front":np.array([[800.0, 214.35935394, 0.0, -1200.0], [450.0, 0.0, -214.35935394, -139.10161515000004], [1.0, 0.0, 0.0, -1.5], [0.0, 0.0, 0.0, 1.0]]),
    "rgb_left":np.array([[214.35935394, -800.0, 0.0, -240.0], [0.0, -450.0, -214.35935394, 400.89838484999996], [0.0, -1.0, 0.0, -0.3], [0.0, 0.0, 0.0, 1.0]]),
    "rgb_right":np.array([[-214.35935394, 800.0, 0.0, -240.0], [0.0, 450.0, -214.35935394, 400.89838484999996], [0.0, 1.0, 0.0, -0.3], [0.0, 0.0, 0.0, 1.0]]),
    "rgb_back":np.array([[-800.0, -214.35935394, 0.0, -1280.0], [-450.0, 0.0, -214.35935394, -184.10161515000007], [-1.0, 0.0, 0.0, -1.6], [0.0, 0.0, 0.0, 1.0]])
}. I wonder how to get the  matrix?

**Comment by jiaxiaosong1002** [comment]
Thanks for your interests.

Note that in our coordinate system, Lidar == Ego Coordinate system.

Please read the start of our [calibration process](https://github.com/OpenDriveLab/DriveAdapter/blob/main/camera_calibration/calculate_distortion_parameters.py) to know how to calculate the intrinsics of the camera and obtain the coordinate of each camera (for extrinsics) in our [data collection code](https://github.com/OpenDriveLab/DriveAdapter/blob/main/leaderboard/team_code/roach_ap_agent_data_collection.py). 

After obtaining the intrinsics and extrinsics of the camera (maybe further calibrated by our code), you could obtain the final matrix. You may need some introduction level of knowledge of Computer Vision, which could be learnt from any textbook or blogs.

**Comment by raozhongyu** [comment]
Thanks a lot
