### ISSUE TITLE
only train the adapter but freeze the student model?

### ISSUE THREAD

**Issue by eson88866** [OpenDriveLab/DriveAdapter#4]
Hello, I have some questions. 
If we use Roach(same BEV) as the teacher model to train the DriveAdapter model, is it necessary to retrain the student model as well? 
What I mean is, can we also freeze the student model's weights and only train the adapter? Is this a good approach?
It seems like it could significantly reduce training time.
Assuming my understanding is correct, would using other teacher models like PlanT result in differences in the student model's perception segmentation task?

I really like your research. Thank you very much.

**Comment by jiaxiaosong1002** [comment]
Hi, thanks for your interests.

We have not tried any of your idea.

However, your understand is correct. One significant advantage of the DriveAdapter paradigm is that it decouples the perception, planning, and sim2real part which teacher, student, and adapter are responsible for respectively while still maintaining the end-to-end ability.

Thus,  you are welcomed to try your idea and report results here. We are glad to hear about more.
