### ISSUE TITLE
Segmentation fault (core dumped); collect_data.sh; 1080ti 

### ISSUE THREAD

**Issue by eson88866** [OpenDriveLab/DriveAdapter#5]
I want to perform data collection on "i7-10700+1080ti_11G+D4_32G"
But no matter what I try, I will encounter "Segmentation fault" after just collecting a few frames.
According to observation, the memory and Vram are sufficient, and the same fault occurs on all my 1080ti and 2080ti. What is the problem? Even if I use gdb, I cannot find the problem.

I guess which part of the code pre-plans the Vram space position that is too large? As a result, GPUs below 3090 cannot be used.
Thank!
![error](https://github.com/OpenDriveLab/DriveAdapter/assets/80897512/cadbbe67-11e3-40ac-a869-5b701b8885f3)

**Comment by jiaxiaosong1002** [comment]
@eson88866 
Thnaks for your interesets. It is a know issue of CARLA, as discussed in the issue section. You may want to check their solutions.

The GPU memory should not be a big problem. During data collection, it only requires ~4GB GPU memory.

 Ubuntu 18.04 and Python3.7 is a safe choice. Do not use root user to run CARLA.

**Comment by ChengkaiYang** [comment]
> @eson88866 Thnaks for your interesets. It is a know issue of CARLA, as discussed in the issue section. You may want to check their solutions.
> 
> The GPU memory should not be a big problem. During data collection, it only requires ~4GB GPU memory.
> 
> Ubuntu 18.04 and Python3.7 is a safe choice. Do not use root user to run CARLA.

Sorry to distrub you.I would like to know are interaction multi-agent prediction competition available now?Recently,i have submitted my result on the https://challenge.interaction-dataset.com/upload/ but might got no reply and no results shown on the leaderboard.I would like to know where to check my submission log pages?Thanks!

**Comment by eson88866** [comment]
> > @eson88866 Thnaks for your interesets. It is a know issue of CARLA, as discussed in the issue section. You may want to check their solutions.
> > The GPU memory should not be a big problem. During data collection, it only requires ~4GB GPU memory.
> > Ubuntu 18.04 and Python3.7 is a safe choice. Do not use root user to run CARLA.
> 
> Sorry to distrub you.I would like to know are interaction multi-agent prediction competition available now?Recently,i have submitted my result on the https://challenge.interaction-dataset.com/upload/ but might got no reply and no results shown on the leaderboard.I would like to know where to check my submission log pages?Thanks!

Sorry I don't know about this competition

**Comment by jiaxiaosong1002** [comment]
@ChengkaiYang 
Hi, I do not work with the INTERACTION dataset team and am not updated about the challenge since 2021. Please contact the organizers of the chanllge.

**Comment by jiaxiaosong1002** [comment]
@eson88866

Hi, https://github.com/OpenDriveLab/ThinkTwice/issues/3#issuecomment-1885230465 might solve your issue!
