### ISSUE TITLE
Running in Ubuntu 22.04 with a higher version of CUDA 

### ISSUE THREAD

**Issue by thunguyenth** [OpenDriveLab/DriveAdapter#6]
Hi,
Thank you for sharing your work.
I am trying to run the code in Ubuntu 22.04.
**System details**:
OS: Ubuntu 22.04 LTS
CUDA: 12.3

However, Ubuntu 22,04 only supports CUDA version >=11.7, while the default CUDA version of this DriveAdapter repo seems to be 11.3.
I tried installing the _cudatoolkit_ package (version 11,3) in the conda environment, but there is an error when running the setup.py file.
**_Error:_**
> The detected CUDA version (12.3) mismatches the version that was used to compile
> PyTorch (11.3). Please make sure to use the same CUDA versions.

**_Question_**:
1. Is there any method that I can use to either:
- Run the code with CUDA version >=11.7
- Run the code in Ubuntu 22.04
2. What is the fixed required setting: The CUDA version must be 11.3? or the Pytorch version must be 1.12.1?

Thank you!

**Comment by jiaxiaosong1002** [comment]
@thunguyenth 
Yes. The cuda version must be 11.3 as the dependency for mmcv and mmdet3d is quite complex. 

However, if you are familiar with the installation of mm series, it may work with higher version of Pytorch and cuda with some minor modifications of the code.  There is no specific operators has certain cuda dependency.

**Comment by thunguyenth** [comment]
@jiaxiaosong1002 
Thank you for your help!
