### ISSUE TITLE
Town05 Long benchmark results

### ISSUE THREAD

**Issue by YzMark2r** [OpenDriveLab/DriveAdapter#7]
We would like to cite your paper, but usually Town05 Long benchmark requires three experimental results. Could you please publish the results of the DriveAdapter (model with results of 61.7/92.3/0.69) for two additional experiments？Thank you very much for your help.

**Comment by jiaxiaosong1002** [comment]
@YzMark2r 
Hi, thanks for your interest. You might run the checkpoint by yourself and I would like to help if there is any issue.
